package gofiledag

import (
	"go/parser"
	"go/token"
	"testing"
)

func TestIsGenerated(t *testing.T) {
	for _, c := range []struct {
		name string
		src  string
		want bool
	}{
		{
			name: "standard marker",
			src:  "// Code generated by foo. DO NOT EDIT.\n\npackage test\n",
			want: true,
		},
		{
			name: "marker with extra prose",
			src:  "// Some doc\n\n// Code generated by stringer; DO NOT EDIT.\n\npackage test\n",
			want: true,
		},
		{
			name: "marker after package clause is ignored",
			src:  "package test\n\n// Code generated by foo. DO NOT EDIT.\n",
			want: false,
		},
		{
			name: "not a marker",
			src:  "// just a comment\n\npackage test\n",
			want: false,
		},
	} {
		t.Run(c.name, func(t *testing.T) {
			fset := token.NewFileSet()
			f, err := parser.ParseFile(fset, "x.go", c.src, parser.ParseComments)
			if err != nil {
				t.Fatalf("parse: %v", err)
			}
			if got := isGenerated(f); got != c.want {
				t.Errorf("isGenerated(%q) = %v, want %v", c.name, got, c.want)
			}
		})
	}
}
